# Generated by Django 2.1.1 on 2018-11-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songcloud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realroom',
            name='roomtype',
        ),
        migrations.RemoveField(
            model_name='virtualroom',
            name='roomtype',
        ),
    ]
