# Generated by Django 2.1.1 on 2018-11-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songcloud', '0002_auto_20181119_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='realroom',
            name='currentSong',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='songinroom',
            name='idInRoom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtualroom',
            name='currentSong',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
