# Generated by Django 2.1.1 on 2018-11-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songcloud', '0003_auto_20181119_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roomid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='roomtype',
            field=models.IntegerField(default=0),
        ),
    ]
