# Generated by Django 2.1.1 on 2018-11-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songcloud', '0004_auto_20181129_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='realroom',
            name='currentTime',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='virtualroom',
            name='currentTime',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
